SERVICE_WORKS = 'Service works'
DATETIME_TEMPLATE = '%Y-%m-%dT%H:%M:%SZ'
BAD_MESSAGE = 'BAD REQUEST'
INVALID_CONDITION = 'invalid condition'
COMPLETE_MESSAGE = 'Completed'
USER_NOT_AUTH = 'user not authenticate'

PARAM_MANY_DATA_ALLOW = 'many'
PARAM_OUT_WITH_HISTORY = 'with_history'
PARAM_COND_BEFORE = 'complete_before'
PARAM_COND_AFTER = 'complete_after'
PARAM_COND_STATUS = 'status'

PARAM_USER_NAME = 'username'
PARAM_USER_PASSWORD = 'password'
