# Generated by Django 3.1.1 on 2020-09-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completion_date',
            new_name='completion_time',
        ),
    ]
