# Generated by Django 3.1.1 on 2020-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gen',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('planned', 'Planned'), ('in work', 'In Work'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
