# Generated by Django 3.1.1 on 2020-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_gen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gen',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
