# Generated by Django 3.1.1 on 2020-09-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_auto_20200929_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('planned', 'Planned'), ('in work', 'In Work'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
